# Generated by Django 6.0.4 on 2026-04-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_add_avatar_to_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
