# Generated by Django 6.0.4 on 2026-04-20 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in list view', max_length=300)),
                ('body', models.TextField(help_text='HTML content — use plain HTML tags')),
                ('image_url', models.CharField(blank=True, help_text='Optional hero image URL', max_length=500)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
