from django.db import migrations

BODY = """<p><strong>If you've gotten a junk removal quote in Nashville lately and thought the price felt higher than you expected — you're not imagining it.</strong> Starting around 2022, disposal costs for commercial haulers in Middle Tennessee began rising in ways that were quiet, structural, and largely invisible to the average homeowner. This post explains what changed, why it matters, and what Junk Busters does to keep your estimate as competitive as possible.</p>

<hr>

<h2>What Is the Southern Services Landfill — and Why Does It Matter?</h2>

<p>Until 2022, Nashville's independent junk removal companies — including Junk Busters — had access to Waste Management's Southern Services C&amp;D landfill in Bordeaux, a neighborhood in northwest Davidson County. It was the only commercial construction and demolition (C&amp;D) landfill in Davidson County. "C&amp;D debris" includes everything generated by renovation and demolition work: drywall, lumber, concrete, roofing, and large mixed loads from property cleanouts.</p>

<p>A C&amp;D landfill accepting third-party commercial loads is a critical piece of infrastructure for any city with an active housing market. Nashville has one of the most active housing markets in the country. And then that access went away.</p>

<h2>The Contractor Ban — and the Court Decision</h2>

<p>Around 2022, Southern Services began restricting access to preserve remaining capacity for WM's own fleet. Third-party haulers — every independent junk removal company in the city — were effectively locked out. This wasn't widely publicized. It showed up on haulers' bills, not on the news.</p>

<p>Then in September 2023, the Tennessee Court of Appeals denied Southern Services' permit to expand the landfill. Without expansion and without third-party access, the situation became permanent rather than temporary. WM has announced plans for a recycling transfer facility to partially offset the loss, but it doesn't solve commercial C&amp;D disposal for independent haulers in the near term.</p>

<p>The result: every independent junk removal company in Nashville must now drive to a landfill in Williamson, Sumner, Rutherford, Wilson, Cheatham, or another surrounding county to dispose of C&amp;D debris and large mixed loads. That means longer drives, more fuel, and higher tipping fees — all of which factor into the price of your estimate.</p>

<h2>The Regional Ripple Effects</h2>

<p>The Southern Services situation didn't just affect Nashville haulers. It added volume pressure to every surrounding county's landfill. And some of those facilities have had their own challenges:</p>

<h3>Sumner County Resource Authority Fire — April 2024</h3>
<p>On April 14, 2024, a hydraulic hose burst caused a fire in the tipping area at the Resource Authority of Sumner County — the primary disposal facility for Gallatin, Hendersonville, Portland, and all of Sumner County. The facility closed for repairs. Since reopening, Sumner County now charges for <strong>both mattresses AND box springs</strong> separately — not just mattresses. Current rates: <strong>$75/ton for in-county waste and $85/ton for out-of-county waste</strong>. The extra mattress and box spring charges are something we pass through at cost on any relevant job.</p>

<h3>Middle Point Landfill Capacity Crisis — Rutherford County</h3>
<p>Middle Point Landfill on Landfill Road in Rutherford County is one of the largest disposal facilities in Middle Tennessee. It currently serves <strong>34 counties</strong>. The problem: it is projected to reach capacity within 4–6 years. The Rutherford County Commission has proposed capping the amount of out-of-county waste — particularly from Davidson County — it accepts, in order to extend the landfill's operational life for Rutherford County residents. Current gate rate: <strong>$99/ton minimum</strong>. Junk Busters maintains a commercial account with volume-based rate reductions, but the base rate is what it is. When Middle Point limits intake or closes, every hauler in the region will have fewer options and prices will rise further.</p>

<h3>Williamson County — Highest Rates in the Primary Service Area</h3>
<p>Williamson County Landfill charges <strong>$75/ton</strong> — the highest general tipping rate in our primary Tennessee service area. Effective April 1, 2024, the county began charging <strong>$20 per mattress and $20 per box spring</strong> separately. Jobs in Franklin, Brentwood, Spring Hill, and Nolensville are routed here, and we're transparent about it on every estimate.</p>

<h2>County-by-County Tipping Fee Table (Current as of Early 2026)</h2>

<table style="width:100%;border-collapse:collapse;font-size:14px;line-height:1.5;margin:16px 0;">
  <thead>
    <tr style="background:#1e3a5f;color:#fff;">
      <th style="padding:10px 14px;text-align:left;">County</th>
      <th style="padding:10px 14px;text-align:left;">Facility</th>
      <th style="padding:10px 14px;text-align:left;">Rate</th>
      <th style="padding:10px 14px;text-align:left;">Mattress / Box Spring</th>
    </tr>
  </thead>
  <tbody>
    <tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Davidson, TN</td><td style="padding:10px 14px;">Omohundro (residential only; commercial routed out-of-county)</td><td style="padding:10px 14px;">$20/2 cu yd max</td><td style="padding:10px 14px;">Varies</td></tr>
    <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Sumner, TN</td><td style="padding:10px 14px;">Resource Authority of Sumner County</td><td style="padding:10px 14px;">$75/ton in-county · $85/ton out-of-county</td><td style="padding:10px 14px;">Charged separately (post-fire policy)</td></tr>
    <tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Williamson, TN</td><td style="padding:10px 14px;">Williamson County Landfill</td><td style="padding:10px 14px;">$75/ton</td><td style="padding:10px 14px;">$20 each (eff. April 2024)</td></tr>
    <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Montgomery, TN</td><td style="padding:10px 14px;">Bi-County Solid Waste</td><td style="padding:10px 14px;">$48/ton (&gt;2,500 lbs)</td><td style="padding:10px 14px;">$10 each</td></tr>
    <tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Rutherford, TN</td><td style="padding:10px 14px;">Middle Point Landfill</td><td style="padding:10px 14px;">$99/ton minimum (volume discount acct)</td><td style="padding:10px 14px;">Charged separately</td></tr>
    <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Wilson, TN</td><td style="padding:10px 14px;">Wilson County Landfill</td><td style="padding:10px 14px;">$18/cu yd C&amp;D · $100/ton shingles</td><td style="padding:10px 14px;">Charged separately</td></tr>
    <tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Cheatham, TN</td><td style="padding:10px 14px;">Cheatham County Solid Waste</td><td style="padding:10px 14px;">$77/ton (eff. July 2025)</td><td style="padding:10px 14px;">Charged separately</td></tr>
    <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Robertson, TN</td><td style="padding:10px 14px;">Robertson County</td><td style="padding:10px 14px;">$65/ton in-county · $75/ton out-of-county</td><td style="padding:10px 14px;">Charged separately</td></tr>
    <tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Logan, KY</td><td style="padding:10px 14px;">Logan County Solid Waste</td><td style="padding:10px 14px;">$38/ton (eff. Sept 2024)</td><td style="padding:10px 14px;">Charged separately</td></tr>
    <tr style="background:#f8fafc;border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Simpson, KY</td><td style="padding:10px 14px;">Simpson Co. Convenience Center</td><td style="padding:10px 14px;">$45/yard C&amp;D · $25 large truck load</td><td style="padding:10px 14px;">Charged separately</td></tr>
    <tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:10px 14px;font-weight:600;">Allen, KY</td><td style="padding:10px 14px;">Allen County Landfill</td><td style="padding:10px 14px;">$51.50/ton</td><td style="padding:10px 14px;">Charged separately</td></tr>
    <tr style="background:#f8fafc;"><td style="padding:10px 14px;font-weight:600;">Warren, KY</td><td style="padding:10px 14px;">Benson Valley Landfill</td><td style="padding:10px 14px;">Commercial tonnage (quote required)</td><td style="padding:10px 14px;">Charged separately</td></tr>
  </tbody>
</table>

<h2>Surcharges Explained</h2>

<p>Beyond the base tipping rate, certain items carry additional per-item fees at the gate. These aren't Junk Busters fees — they're fees set by the county landfill that we pass through at cost:</p>

<ul>
  <li><strong>Mattresses:</strong> $10–$20 each depending on county. All counties in our service area now charge a mattress disposal fee.</li>
  <li><strong>Box springs:</strong> Charged separately at facilities that distinguish them — including Sumner County (post-fire) and Williamson County ($20 each).</li>
  <li><strong>Shingles:</strong> Up to $100/ton at some facilities (Wilson County Landfill). Shingle-heavy loads cost significantly more to dispose of.</li>
  <li><strong>Tires:</strong> Charged separately at most facilities.</li>
  <li><strong>Freon appliances:</strong> Must be degassed by a certified technician before disposal.</li>
</ul>

<h2>Tarping Laws</h2>

<p>Tennessee law requires all loads to be covered. Uncovered loads can result in fines of $20–$50 per violation. We tarp every load — not just because the law requires it, but because debris falling from an uncovered truck is a genuine road hazard. We've never cut this corner and we never will.</p>

<h2>What Junk Busters Does Differently</h2>

<p>We've been dumping at facilities across this region every week for years. We know the gate staff at Middle Point. We know the weigh-in procedures at Sumner County. We monitor facility policy changes — like the Sumner fire and the Williamson mattress fee — as they happen, not months later. That operational knowledge is what lets us quote accurately.</p>

<ul>
  <li><strong>Upfront quotes before we start</strong> — you know the price before we lift anything.</li>
  <li><strong>Disposal fees passed through at cost</strong> — we don't markup landfill surcharges.</li>
  <li><strong>Commercial accounts at multiple facilities</strong> — volume-based rate reductions we pass along where we can.</li>
  <li><strong>No hidden fees</strong> — the quote is the price.</li>
</ul>

<p>The waste disposal situation across Middle Tennessee is genuinely complicated right now. Southern Services is locked. Middle Point is running out of room. Sumner County had a fire. Williamson County rates are high. We can't fix any of that. What we can do is be honest about it — and give you an accurate quote that reflects reality so you're not surprised at the end of a job.</p>

<hr>

<p><strong>Ready to get an estimate?</strong> Call <a href="tel:6158812505">615-881-2505</a> or <a href="/quote/">submit a quote request online</a>. We serve Nashville, Clarksville, Bowling Green KY, and communities across Middle Tennessee and Southern Kentucky. We'll tell you exactly what the job costs — including any applicable disposal fees — before we start.</p>"""


def seed_blog(apps, schema_editor):
    BlogPost = apps.get_model('website', 'BlogPost')
    if not BlogPost.objects.filter(slug='nashville-waste-crisis-junk-removal-costs').exists():
        BlogPost.objects.create(
            title='Why Junk Removal Costs More in Nashville: The Waste Crisis Explained',
            slug='nashville-waste-crisis-junk-removal-costs',
            excerpt=(
                "Nashville’s only C&D landfill stopped accepting third-party contractors. "
                "The Sumner County Resource Authority had a fire. Middle Point Landfill is "
                "running out of room. Here’s what’s actually happening to disposal "
                "costs — and what Junk Busters is doing about it."
            ),
            body=BODY,
            is_live=True,
        )


def unseed_blog(apps, schema_editor):
    BlogPost = apps.get_model('website', 'BlogPost')
    BlogPost.objects.filter(slug='nashville-waste-crisis-junk-removal-costs').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_add_giftcard_model'),
    ]

    operations = [
        migrations.RunPython(seed_blog, unseed_blog),
    ]
