from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'website'

# 301 redirects for old/renamed slugs that Google may have indexed.
# permanent=True issues a 301 so Google transfers ranking signals to the new URL.
_R = lambda old, new: path(old, RedirectView.as_view(url=f'/{new}/', permanent=True))

LEGACY_REDIRECTS = [
    # Service page renames
    _R('shed-demolition',           'light-demolition'),
    _R('airbnb-cleaning',           'short-term-rental-turnover'),
    _R('air-bnb',                   'short-term-rental-turnover'),
    _R('short-term-rental',         'short-term-rental-turnover'),
    _R('move-in-out-cleaning',      'move-out-deep-cleaning'),
    _R('move-in-move-out',          'move-out-deep-cleaning'),
    _R('moving-cleaning',           'move-out-deep-cleaning'),
    _R('scrap-metal',               'scrap-metal-pickup'),
    _R('dump-trailer',              'dump-trailer-rental'),
    _R('hoarder-cleanout',          'estate-hoarder-cleanout'),
    _R('estate-cleanout',           'estate-clean-out'),
    _R('eviction-cleanout',         'eviction-clean-out'),
    _R('foreclosure-cleanout',      'foreclosure-clean-out'),
    _R('garage-cleanout',           'garage-clean-out'),
    _R('storage-unit',              'storage-unit-clean-out'),
    _R('storage-cleanout',          'storage-unit-clean-out'),
    _R('hot-tub',                   'hot-tub-removal'),
    _R('hot-tub-removal-service',   'hot-tub-removal'),
    _R('property-manager',          'property-manager-hub'),
    _R('bulk-cardboard',            'bulk-cardboard-removal'),
    _R('fence',                     'fence-removal'),
    _R('junk-removal-services',     'junk-removal'),
    _R('residential-junk-removal',  'junk-removal'),
    _R('light-demo',                'light-demolition'),
    _R('demolition',                'light-demolition'),
    # City pages without state suffix → canonical with suffix
    _R('junk-removal-nashville-tn',        'junk-removal-nashville'),
    _R('junk-removal-clarksville-tn',      'junk-removal-clarksville'),
    _R('junk-removal-bowling-green-ky',    'junk-removal-bowling-green'),
    _R('junk-removal-white-house',         'junk-removal-white-house-tn'),
    _R('junk-removal-hendersonville',      'junk-removal-hendersonville-tn'),
    _R('junk-removal-gallatin',            'junk-removal-gallatin-tn'),
    _R('junk-removal-springfield',         'junk-removal-springfield-tn'),
    _R('junk-removal-franklin',            'junk-removal-franklin-tn'),
    _R('junk-removal-goodlettsville',      'junk-removal-goodlettsville-tn'),
    _R('junk-removal-portland',            'junk-removal-portland-tn'),
    _R('junk-removal-murfreesboro',        'junk-removal-murfreesboro-tn'),
    _R('junk-removal-smyrna',              'junk-removal-smyrna-tn'),
    _R('junk-removal-lavergne',            'junk-removal-lavergne-tn'),
    _R('junk-removal-lebanon',             'junk-removal-lebanon-tn'),
    _R('junk-removal-russellville',        'junk-removal-russellville-ky'),
    _R('junk-removal-franklin-ky-tn',      'junk-removal-franklin-ky'),
    _R('junk-removal-scottsville',         'junk-removal-scottsville-ky'),
    _R('junk-removal-brentwood',           'junk-removal-brentwood-tn'),
    _R('junk-removal-spring-hill',         'junk-removal-spring-hill-tn'),
    _R('junk-removal-mt-juliet',           'junk-removal-mt-juliet-tn'),
    _R('junk-removal-nolensville',         'junk-removal-nolensville-tn'),
    _R('junk-removal-ashland-city',        'junk-removal-ashland-city-tn'),
]

urlpatterns = [
    path('', views.home, name='home'),
    path('services/', views.services, name='services'),
    path('quote/', views.quote, name='quote'),
    path('quote/success/', views.quote_success, name='quote_success'),
    path('book/', views.booking, name='booking'),
    path('book/success/', views.booking_success, name='booking_success'),
    path('areas-we-serve/', views.areas, name='areas'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('loyalty/', views.loyalty, name='loyalty'),
    path('track/', views.track, name='track'),
    path('referral/', views.referral, name='referral'),
    path('api/chat/', views.chat_proxy, name='chat_proxy'),
    path('api/chat/poll/', views.chat_poll, name='chat_poll'),
    path('api/service-area-map/', views.service_area_geojson, name='service_area_geojson'),
    path('api/embed/member-signup/', views.member_signup_webhook, name='member_signup_webhook'),
    path('sitemap.xml', views.sitemap, name='sitemap'),
    path('robots.txt', views.robots, name='robots'),
    path('llms.txt', views.llms_txt, name='llms_txt'),
    path('health/', views.health, name='health'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('pricing/', views.pricing, name='pricing'),
    path('faq/', views.faq, name='faq'),
    # City landing pages — before catch-all
    path('junk-removal-clarksville/', views.city_clarksville, name='city_clarksville'),
    path('junk-removal-bowling-green/', views.city_bowling_green, name='city_bowling_green'),
    path('kentucky/', views.city_kentucky, name='city_kentucky'),
    path('junk-removal-nashville/', views.city_nashville, name='city_nashville'),
    path('junk-removal-white-house-tn/', views.city_white_house, name='city_white_house'),
    path('junk-removal-hendersonville-tn/', views.city_hendersonville, name='city_hendersonville'),
    path('junk-removal-gallatin-tn/', views.city_gallatin, name='city_gallatin'),
    path('junk-removal-springfield-tn/', views.city_springfield, name='city_springfield'),
    path('junk-removal-franklin-tn/', views.city_franklin, name='city_franklin'),
    path('junk-removal-goodlettsville-tn/', views.city_goodlettsville, name='city_goodlettsville'),
    path('junk-removal-portland-tn/',       views.city_portland,       name='city_portland'),
    path('junk-removal-murfreesboro-tn/',   views.city_murfreesboro,   name='city_murfreesboro'),
    path('junk-removal-smyrna-tn/',         views.city_smyrna,         name='city_smyrna'),
    path('junk-removal-lavergne-tn/',       views.city_lavergne,       name='city_lavergne'),
    path('junk-removal-lebanon-tn/',        views.city_lebanon,        name='city_lebanon'),
    path('junk-removal-russellville-ky/',   views.city_russellville,   name='city_russellville'),
    path('junk-removal-franklin-ky/',       views.city_franklin_ky,    name='city_franklin_ky'),
    path('junk-removal-scottsville-ky/',    views.city_scottsville,    name='city_scottsville'),
    path('junk-removal-brentwood-tn/',      views.city_brentwood,      name='city_brentwood'),
    path('junk-removal-spring-hill-tn/',    views.city_spring_hill,    name='city_spring_hill'),
    path('junk-removal-mt-juliet-tn/',      views.city_mt_juliet,      name='city_mt_juliet'),
    path('junk-removal-nolensville-tn/',    views.city_nolensville,    name='city_nolensville'),
    path('junk-removal-ashland-city-tn/',   views.city_ashland_city,   name='city_ashland_city'),
    # Gift cards
    path('gift-card/',          views.gift_card_purchase, name='gift_card'),
    path('gift-card/success/',  views.gift_card_success,  name='gift_card_success'),
    path('gift-card/webhook/',  views.gift_card_webhook,  name='gift_card_webhook'),
    path('gift-card/check/',    views.gift_card_check,    name='gift_card_check'),
    # Legacy redirects — must come before catch-all
    *LEGACY_REDIRECTS,
    # Individual service pages — must come last (catch-all slug)
    path('<slug:slug>/', views.service_page, name='service_page'),
]
